import type {
  AvatarType,
  BodyShape,
  BrandArchetype,
  BrandDnaContent,
  AvatarConcept,
} from '@pixel/contracts';

type ShapeLanguage = BrandDnaContent['visualLanguage']['shapeLanguage'];
type Temperature = BrandDnaContent['visualLanguage']['temperature'];
type RenderHints = AvatarConcept['renderHints'];

export interface SubjectDefinition {
  id: string;
  /** "grano de café" */
  label: string;
  /** Género gramatical de `label` (para "el/la", "convertido/a"). */
  feminine: boolean;
  /** Nombre corto para el nombre conceptual: "Grano". */
  short: string;
  /** Frase que abre el concepto: "Grano de café". */
  phrase: string;
  avatarType: AvatarType;
  /** Raíces normalizadas (sin tildes, minúsculas) que buscan en el texto del ADN. */
  keywords: string[];
  /** Si una restricción o algo a evitar menciona alguno de estos términos, el sujeto se descarta. */
  vetoTerms: string[];
  shapeAffinity: ShapeLanguage[];
  archetypeAffinity: BrandArchetype[];
  temperature?: Temperature;
  bodyShape: BodyShape;
  proportions: { width: number; height: number; depth: number };
  render: Pick<RenderHints, 'archetype' | 'roundness' | 'surfaceDetail'>;
  /** Material propio del sujeto: "grano tostado". */
  material: string;
  accessoryIdeas: string[];
  /** Matiz para nombrar colores: "marrón" → "marrón café". */
  colorQualifiers?: Record<string, string>;
}

/**
 * Catálogo de sujetos. Extensible: añadir un sujeto = añadir una entrada.
 * Ningún campo por sí solo decide: el motor puntúa cada sujeto combinando varias señales del ADN.
 */
export const SUBJECTS: SubjectDefinition[] = [
  {
    id: 'coffee_bean',
    label: 'grano de café',
    feminine: false,
    short: 'Grano',
    phrase: 'Grano de café',
    avatarType: 'anthropomorphic_object',
    keywords: ['cafe', 'tinto', 'espresso', 'barista', 'tostad', 'caficult', 'cafeter', 'cafetal'],
    vetoTerms: ['grano'],
    shapeAffinity: ['organic', 'soft'],
    archetypeAffinity: ['creator', 'caregiver', 'everyman', 'explorer'],
    temperature: 'warm',
    bodyShape: 'oval',
    proportions: { width: 0.9, height: 1.15, depth: 0.8 },
    render: { archetype: 'seed', roundness: 0.85, surfaceDetail: 'center_groove' },
    material: 'grano tostado',
    accessoryIdeas: ['Hoja de cafeto como detalle', 'Pequeña taza de tinto'],
    colorQualifiers: { marrón: 'café' },
  },
  {
    id: 'cacao_pod',
    label: 'mazorca de cacao',
    feminine: true,
    short: 'Cacao',
    phrase: 'Mazorca de cacao',
    avatarType: 'anthropomorphic_object',
    keywords: ['cacao', 'chocolat', 'bombon', 'confiter'],
    vetoTerms: ['mazorca'],
    shapeAffinity: ['organic', 'soft'],
    archetypeAffinity: ['creator', 'lover', 'caregiver'],
    temperature: 'warm',
    bodyShape: 'oval',
    proportions: { width: 0.95, height: 1.2, depth: 0.9 },
    render: { archetype: 'seed', roundness: 0.75, surfaceDetail: 'grain' },
    material: 'cáscara de cacao',
    accessoryIdeas: ['Semillas de cacao como botones', 'Lazo de fibra natural'],
    colorQualifiers: { marrón: 'chocolate' },
  },
  {
    id: 'bread_loaf',
    label: 'pan artesanal',
    feminine: false,
    short: 'Miga',
    phrase: 'Pan artesanal',
    avatarType: 'anthropomorphic_object',
    keywords: ['pan', 'panader', 'pasteler', 'horno', 'reposter', 'masa madre'],
    vetoTerms: ['pan '],
    shapeAffinity: ['soft', 'organic'],
    archetypeAffinity: ['caregiver', 'everyman', 'creator'],
    temperature: 'warm',
    bodyShape: 'rounded',
    proportions: { width: 1.15, height: 0.9, depth: 0.95 },
    render: { archetype: 'blob', roundness: 0.9, surfaceDetail: 'grain' },
    material: 'corteza horneada',
    accessoryIdeas: ['Espiga de trigo', 'Delantal mínimo de lino'],
  },
  {
    id: 'leaf',
    label: 'hoja viva',
    feminine: true,
    short: 'Hoja',
    phrase: 'Hoja viva',
    avatarType: 'organic_character',
    keywords: [
      'hoja',
      'planta',
      'jardin',
      'botanic',
      'te ',
      'infusion',
      'herbal',
      'sostenib',
      'ecolog',
      'reciclaj',
      'bosque',
    ],
    vetoTerms: ['hoja'],
    shapeAffinity: ['organic', 'fluid'],
    archetypeAffinity: ['innocent', 'caregiver', 'explorer'],
    bodyShape: 'teardrop',
    proportions: { width: 0.85, height: 1.2, depth: 0.6 },
    render: { archetype: 'drop', roundness: 0.7, surfaceDetail: 'veins' },
    material: 'fibra vegetal',
    accessoryIdeas: ['Gota de rocío', 'Pequeño brote'],
  },
  {
    id: 'sprout',
    label: 'semilla que germina',
    feminine: true,
    short: 'Brote',
    phrase: 'Semilla que germina',
    avatarType: 'organic_character',
    keywords: [
      'agro',
      'agricol',
      'cultivo',
      'semilla',
      'cosecha',
      'campo',
      'crecimiento',
      'educaci',
      'aprendiz',
    ],
    vetoTerms: ['semilla'],
    shapeAffinity: ['organic', 'soft'],
    archetypeAffinity: ['innocent', 'caregiver', 'explorer', 'sage'],
    bodyShape: 'oval',
    proportions: { width: 0.95, height: 1.05, depth: 0.95 },
    render: { archetype: 'seed', roundness: 0.9, surfaceDetail: 'none' },
    material: 'semilla pulida',
    accessoryIdeas: ['Brote de dos hojas', 'Raíces suaves como pies'],
  },
  {
    id: 'water_drop',
    label: 'gota',
    feminine: true,
    short: 'Gota',
    phrase: 'Gota',
    avatarType: 'organic_character',
    keywords: [
      'agua',
      'bebida',
      'jugo',
      'limpieza',
      'spa',
      'cosmetic',
      'belleza',
      'skincare',
      'hidrata',
      'piscina',
    ],
    vetoTerms: ['gota'],
    shapeAffinity: ['fluid', 'soft'],
    archetypeAffinity: ['innocent', 'lover', 'caregiver'],
    temperature: 'cool',
    bodyShape: 'teardrop',
    proportions: { width: 0.9, height: 1.15, depth: 0.9 },
    render: { archetype: 'drop', roundness: 0.95, surfaceDetail: 'none' },
    material: 'superficie líquida',
    accessoryIdeas: ['Reflejo brillante', 'Burbujas pequeñas'],
  },
  {
    id: 'health_capsule',
    label: 'cápsula de bienestar',
    feminine: true,
    short: 'Cápsula',
    phrase: 'Cápsula de bienestar',
    avatarType: 'anthropomorphic_object',
    keywords: [
      'salud',
      'clinic',
      'farmac',
      'medic',
      'hospital',
      'bienestar',
      'odontolog',
      'laborator',
      'nutrici',
    ],
    vetoTerms: ['capsula', 'pastilla'],
    shapeAffinity: ['soft', 'geometric'],
    archetypeAffinity: ['caregiver', 'sage', 'innocent'],
    bodyShape: 'capsule',
    proportions: { width: 0.85, height: 1.2, depth: 0.85 },
    render: { archetype: 'capsule', roundness: 0.8, surfaceDetail: 'panel_lines' },
    material: 'cerámica clínica',
    accessoryIdeas: ['Cruz sutil en el pecho', 'Pequeño estetoscopio'],
  },
  {
    id: 'book',
    label: 'libro',
    feminine: false,
    short: 'Libro',
    phrase: 'Libro',
    avatarType: 'anthropomorphic_object',
    keywords: [
      'libro',
      'editorial',
      'libreri',
      'escuela',
      'colegio',
      'academia',
      'universidad',
      'curso',
    ],
    vetoTerms: ['libro'],
    shapeAffinity: ['structural', 'geometric'],
    archetypeAffinity: ['sage', 'creator', 'explorer'],
    bodyShape: 'blocky',
    proportions: { width: 0.95, height: 1.2, depth: 0.6 },
    render: { archetype: 'block', roundness: 0.35, surfaceDetail: 'panel_lines' },
    material: 'papel y tela de encuadernación',
    accessoryIdeas: ['Marcapáginas como cinta', 'Lentes redondos'],
  },
  {
    id: 'building_block',
    label: 'bloque estructural',
    feminine: false,
    short: 'Bloque',
    phrase: 'Bloque estructural',
    avatarType: 'structural_character',
    keywords: [
      'construc',
      'arquitect',
      'inmobiliar',
      'ingenier',
      'obra',
      'concreto',
      'vivienda',
      'edifici',
      'cemento',
      'ladrillo',
    ],
    vetoTerms: ['bloque', 'ladrillo'],
    shapeAffinity: ['structural', 'geometric'],
    archetypeAffinity: ['ruler', 'hero', 'sage', 'caregiver'],
    bodyShape: 'blocky',
    proportions: { width: 1.1, height: 1.05, depth: 1.0 },
    render: { archetype: 'block', roundness: 0.2, surfaceDetail: 'panel_lines' },
    material: 'concreto pulido',
    accessoryIdeas: [
      'Casco de obra minimalista',
      'Viga como detalle en el hombro',
      'Plano enrollado',
    ],
  },
  {
    id: 'shield',
    label: 'escudo',
    feminine: false,
    short: 'Escudo',
    phrase: 'Escudo',
    avatarType: 'structural_character',
    keywords: [
      'segur',
      'banco',
      'financ',
      'inversi',
      'abogad',
      'legal',
      'proteccion',
      'ciberseguridad',
    ],
    vetoTerms: ['escudo'],
    shapeAffinity: ['structural', 'geometric'],
    archetypeAffinity: ['ruler', 'caregiver', 'hero', 'sage'],
    bodyShape: 'faceted',
    proportions: { width: 1.0, height: 1.1, depth: 0.7 },
    render: { archetype: 'block', roundness: 0.35, surfaceDetail: 'facets' },
    material: 'metal cepillado',
    accessoryIdeas: ['Emblema geométrico', 'Borde dorado fino'],
  },
  {
    id: 'crystal_core',
    label: 'núcleo de cristal',
    feminine: false,
    short: 'Núcleo',
    phrase: 'Núcleo de cristal',
    avatarType: 'geometric_entity',
    keywords: [
      'software',
      'tecnolog',
      'digital',
      'datos',
      'automatiz',
      'plataforma',
      'startup',
      'fintech',
      'ia ',
      'inteligencia artificial',
      'app',
      'saas',
      'nube',
    ],
    vetoTerms: ['cristal'],
    shapeAffinity: ['geometric', 'structural'],
    archetypeAffinity: ['magician', 'sage', 'creator', 'explorer'],
    temperature: 'cool',
    bodyShape: 'faceted',
    proportions: { width: 0.95, height: 1.1, depth: 0.95 },
    render: { archetype: 'crystal', roundness: 0.15, surfaceDetail: 'facets' },
    material: 'cristal facetado',
    accessoryIdeas: ['Anillo orbital de luz', 'Partículas en órbita'],
  },
  {
    id: 'paint_drop',
    label: 'gota de pintura',
    feminine: true,
    short: 'Tinta',
    phrase: 'Gota de pintura',
    avatarType: 'organic_character',
    keywords: [
      'diseno',
      'agencia',
      'publicidad',
      'marketing',
      'arte ',
      'creativ',
      'estudio',
      'ilustraci',
      'fotograf',
    ],
    vetoTerms: ['pintura', 'tinta'],
    shapeAffinity: ['fluid', 'soft', 'organic'],
    archetypeAffinity: ['creator', 'jester', 'rebel', 'magician'],
    bodyShape: 'teardrop',
    proportions: { width: 0.95, height: 1.1, depth: 0.9 },
    render: { archetype: 'drop', roundness: 0.9, surfaceDetail: 'none' },
    material: 'pintura fresca',
    accessoryIdeas: ['Pincel como antena', 'Salpicaduras de color'],
  },
  {
    id: 'thread_spool',
    label: 'carrete de hilo',
    feminine: false,
    short: 'Hilo',
    phrase: 'Carrete de hilo',
    avatarType: 'anthropomorphic_object',
    keywords: ['moda', 'textil', 'ropa', 'confecci', 'costura', 'tejid', 'sastre'],
    vetoTerms: ['carrete', 'hilo'],
    shapeAffinity: ['soft', 'geometric'],
    archetypeAffinity: ['lover', 'creator', 'rebel'],
    bodyShape: 'capsule',
    proportions: { width: 0.9, height: 1.1, depth: 0.9 },
    render: { archetype: 'capsule', roundness: 0.6, surfaceDetail: 'grain' },
    material: 'hilo tejido',
    accessoryIdeas: ['Aguja como accesorio', 'Cinta métrica como bufanda'],
  },
  {
    id: 'paw_creature',
    label: 'criatura de huella',
    feminine: true,
    short: 'Huellita',
    phrase: 'Criatura con forma de huella',
    avatarType: 'creature',
    keywords: ['mascota', 'veterinar', 'perro', 'gato', 'animal'],
    vetoTerms: ['huella', 'animal'],
    shapeAffinity: ['soft', 'organic'],
    archetypeAffinity: ['caregiver', 'jester', 'innocent', 'everyman'],
    bodyShape: 'rounded',
    proportions: { width: 1.1, height: 0.95, depth: 1.0 },
    render: { archetype: 'blob', roundness: 0.95, surfaceDetail: 'none' },
    material: 'pelaje suave',
    accessoryIdeas: ['Collar con placa', 'Orejas redondeadas'],
  },
];

/** Sujetos abstractos: se usan cuando ningún sujeto concreto encaja con suficiente fuerza. */
export const ABSTRACT_SUBJECTS: Record<ShapeLanguage, SubjectDefinition> = {
  organic: abstract(
    'organic_seed',
    'semilla orgánica',
    true,
    'Semilla',
    'Semilla orgánica',
    'organic_character',
    'oval',
    'seed',
    0.85,
    'grain',
    'superficie orgánica',
  ),
  soft: abstract(
    'soft_blob',
    'forma suave',
    true,
    'Nube',
    'Forma suave y amable',
    'abstract_character',
    'rounded',
    'blob',
    0.95,
    'none',
    'superficie suave',
  ),
  fluid: abstract(
    'fluid_drop',
    'gota fluida',
    true,
    'Fluido',
    'Gota fluida',
    'abstract_character',
    'teardrop',
    'drop',
    0.9,
    'none',
    'superficie fluida',
  ),
  geometric: abstract(
    'prism',
    'prisma geométrico',
    false,
    'Prisma',
    'Prisma geométrico',
    'geometric_entity',
    'faceted',
    'crystal',
    0.2,
    'facets',
    'superficie facetada',
  ),
  structural: abstract(
    'monolith',
    'monolito',
    false,
    'Monolito',
    'Monolito estructural',
    'structural_character',
    'blocky',
    'block',
    0.25,
    'panel_lines',
    'volumen sólido',
  ),
  mixed: abstract(
    'soft_blob',
    'forma suave',
    true,
    'Nube',
    'Forma suave y amable',
    'abstract_character',
    'rounded',
    'blob',
    0.95,
    'none',
    'superficie suave',
  ),
};

function abstract(
  id: string,
  label: string,
  feminine: boolean,
  short: string,
  phrase: string,
  avatarType: AvatarType,
  bodyShape: BodyShape,
  archetype: RenderHints['archetype'],
  roundness: number,
  surfaceDetail: RenderHints['surfaceDetail'],
  material: string,
): SubjectDefinition {
  return {
    id,
    label,
    feminine,
    short,
    phrase,
    avatarType,
    keywords: [],
    vetoTerms: [],
    shapeAffinity: [],
    archetypeAffinity: [],
    bodyShape,
    proportions: { width: 1, height: 1, depth: 1 },
    render: { archetype, roundness, surfaceDetail },
    material,
    accessoryIdeas: [],
  };
}

/** Rasgos del personaje según el arquetipo de la marca. */
export const ARCHETYPE_TRAITS: Record<BrandArchetype, string[]> = {
  creator: ['creativo', 'curioso', 'detallista'],
  caregiver: ['amable', 'atento', 'protector'],
  explorer: ['curioso', 'aventurero', 'libre'],
  sage: ['sereno', 'sabio', 'preciso'],
  hero: ['valiente', 'decidido', 'confiable'],
  magician: ['visionario', 'ingenioso', 'sorprendente'],
  rebel: ['atrevido', 'irreverente', 'auténtico'],
  lover: ['elegante', 'apasionado', 'encantador'],
  jester: ['divertido', 'ocurrente', 'espontáneo'],
  everyman: ['cercano', 'honesto', 'sencillo'],
  ruler: ['seguro', 'firme', 'confiable'],
  innocent: ['optimista', 'alegre', 'sincero'],
};

/** Epítetos para el nombre conceptual ("Grano Anfitrión"). */
export const ARCHETYPE_EPITHETS: Record<BrandArchetype, string[]> = {
  creator: ['Artesano', 'Inventor'],
  caregiver: ['Anfitrión', 'Guardián'],
  explorer: ['Viajero', 'Explorador'],
  sage: ['Sabio', 'Mentor'],
  hero: ['Valiente', 'Campeón'],
  magician: ['Visionario', 'Alquimista'],
  rebel: ['Rebelde', 'Disruptor'],
  lover: ['Encantador', 'Esteta'],
  jester: ['Chispa', 'Bromista'],
  everyman: ['Compañero', 'Vecino'],
  ruler: ['Maestro', 'Arquitecto'],
  innocent: ['Soñador', 'Luminoso'],
};

/** Algo que el personaje nunca debería transmitir, según el arquetipo. */
export const ARCHETYPE_GUARDRAILS: Record<BrandArchetype, string> = {
  creator: 'Formas genéricas o de plantilla',
  caregiver: 'Expresiones frías o distantes',
  explorer: 'Poses rígidas o estáticas',
  sage: 'Gestos infantiles o caricaturescos',
  hero: 'Actitud insegura o pasiva',
  magician: 'Estética anticuada o predecible',
  rebel: 'Apariencia corporativa y acartonada',
  lover: 'Acabados toscos o baratos',
  jester: 'Rigidez y seriedad excesiva',
  everyman: 'Lujo ostentoso o pretencioso',
  ruler: 'Gestos infantiles o desordenados',
  innocent: 'Expresiones agresivas u oscuras',
};
